### ISSUE TITLE
WARNING: DATA RACE

### ISSUE THREAD

**Issue by ViRb3** [gofiber/logger#7]
### Versions
```
	github.com/gofiber/fiber v1.10.1
	github.com/gofiber/logger v0.2.0
```

### Issue
When running my program with `-race`, upon initialization of the logger, I get the following data race warning:
```
WARNING: DATA RACE
Read at 0x00c00058bc10 by goroutine 26:
  github.com/gofiber/logger.New.func2.1()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/logger@v0.2.0/main.go:112 +0x18a9
  github.com/valyala/fasttemplate.(*Template).ExecuteFunc()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasttemplate@v1.1.0/template.go:246 +0x4c6
  github.com/gofiber/logger.New.func2()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/logger@v0.2.0/main.go:109 +0x546
  github.com/gofiber/fiber.(*App).next()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber@v1.10.1/router.go:86 +0x5f5
  github.com/gofiber/fiber.(*App).handler()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber@v1.10.1/router.go:99 +0xc7
  github.com/gofiber/fiber.(*App).handler-fm()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber@v1.10.1/router.go:93 +0x6b
  github.com/valyala/fasthttp.(*Server).serveConn()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/server.go:2162 +0x18c4
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/server.go:1953 +0x8c
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/workerpool.go:223 +0x17b
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/workerpool.go:195 +0x61

Previous write at 0x00c00058bc10 by goroutine 24:
  github.com/gofiber/logger.New.func1()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/logger@v0.2.0/main.go:90 +0x11a

Goroutine 26 (running) created at:
  github.com/valyala/fasthttp.(*workerPool).getCh()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/workerpool.go:194 +0x32a
  github.com/valyala/fasthttp.(*workerPool).Serve()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/workerpool.go:147 +0x55
  github.com/valyala/fasthttp.(*Server).Serve()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/server.go:1706 +0xb56
  github.com/gofiber/fiber.(*App).Listen()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber@v1.10.1/app.go:349 +0x760
  main.main()
      [REDACTED]/main.go:15 +0x1fb

Goroutine 24 (running) created at:
  github.com/gofiber/logger.New()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/logger@v0.2.0/main.go:88 +0x46d
  main.main()
      [REDACTED]/main.go:15 +0x1fb
```

This is how I use fiber and the logger:
```go
	app := fiber.New(&fiber.Settings{
		DisableStartupMessage: true,
	})
	app.Use(logger.New())
        ...
        app.Listen(listenAddr)
```

**Comment by Fenny** [comment]
The data race was present in the test file, I fixed this and tagged a minor patch.
<https://github.com/gofiber/logger/releases/tag/v0.2.1>

**Comment by ViRb3** [comment]
I am still getting the same data race warning with version `0.2.1`. It doesn't make sense to me to be a problem in the tests, because I am not running any tests, I am using the logger in a production environment in my program.
```
WARNING: DATA RACE
Read at 0x00c0004e3c10 by goroutine 27:
  github.com/gofiber/logger.New.func2.1()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/logger@v0.2.1/main.go:112 +0x18a9
  github.com/valyala/fasttemplate.(*Template).ExecuteFunc()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasttemplate@v1.1.0/template.go:246 +0x4c6
  github.com/gofiber/logger.New.func2()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/logger@v0.2.1/main.go:109 +0x546
  github.com/gofiber/fiber.(*App).next()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber@v1.10.1/router.go:86 +0x5f5
  github.com/gofiber/fiber.(*App).handler()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber@v1.10.1/router.go:99 +0xc7
  github.com/gofiber/fiber.(*App).handler-fm()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber@v1.10.1/router.go:93 +0x6b
  github.com/valyala/fasthttp.(*Server).serveConn()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/server.go:2162 +0x18c4
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/server.go:1953 +0x8c
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/workerpool.go:223 +0x17b
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/workerpool.go:195 +0x61

Previous write at 0x00c0004e3c10 by goroutine 25:
  github.com/gofiber/logger.New.func1()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/logger@v0.2.1/main.go:90 +0x11a

Goroutine 27 (running) created at:
  github.com/valyala/fasthttp.(*workerPool).getCh()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/workerpool.go:194 +0x32a
  github.com/valyala/fasthttp.(*workerPool).Serve()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/workerpool.go:147 +0x55
  github.com/valyala/fasthttp.(*Server).Serve()
      C:/Users/Admin/go/pkg/mod/github.com/valyala/fasthttp@v1.13.1/server.go:1706 +0xb56
  github.com/gofiber/fiber.(*App).Listen()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/fiber@v1.10.1/app.go:349 +0x760
  main.main()
      [REDACTED]/main.go:15 +0x1fb

Goroutine 25 (running) created at:
  github.com/gofiber/logger.New()
      C:/Users/Admin/go/pkg/mod/github.com/gofiber/logger@v0.2.1/main.go:88 +0x46d
  main.main()
      [REDACTED]/main.go:15 +0x1fb
```

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/logger/pull/9 - PR with fix

**Comment by Fenny** [comment]
Thanks @ReneWerner87, tagged under <https://github.com/gofiber/logger/releases/tag/v0.2.2>

**Comment by ViRb3** [comment]
Confirmed fixed, thanks!
